version: '3'
services:
  artalk:
    environment:
      PYTHONPATH: src/
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'artalk'
    tty: true
    volumes:
      - .:/artalk/