version: '3'
services:
  artalk:
    environment:
      PYTHONPATH: src/
      PYTORCH_CUDA_ALLOC_CONF: max_split_size_mb:512
    ipc: host
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'artalk'
    tty: true
    volumes:
      - .:/artalk/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: all
              device_ids: ['1', '2', '3']
              capabilities: ['gpu']